### ISSUE TITLE
issue on coastal tsunami gauges data output on Tilde

### ISSUE THREAD

**Issue by jeanrog** [GeoNet/help#108]
Hi, 
I am looking at the Raoul Island data on Tilde following the 7.3 earthquake occurring a few minutes ago, and I am surprised by the output of the 2 different channels (40 and 41) on the plot: they should (must) be superimposed, but it looks like they diverge. 

![Tilde_issue_24042023](https://user-images.githubusercontent.com/64455982/233879836-9b8e31af-c6da-44b2-96fc-1055bb793b28.PNG)

**Comment by elidana** [comment]
Hi @jeanrog ,

thanks for your question and please continue to reach out if you see some other oddities.

After some internal consultation with the teams (and thanks heaps to @Cburton90 for his help!!), we did not come to a definitive conclusion, but we can say that this is somewhat expected:
- primary (`40`) and backup (`41`) tsunami monitoring gauges channels are not providing exactly the same output for majority of tsunami gauges we have;
- the digitizer is converting volts to pressure;
- the calibration to convert volts to pressure at a given depth is done in the lab and before the deployment to the best of our conditions;
- each sensor is calibrated so that at 20m depth the instrument record 5V;
- the calibration and won't be exactly the same for each installation once deployed, and some minor differences might be present once sensors are deployed underwater;
- the instrument is measuring pressure changes that might be influenced by local environmental factors or slightly different set up of the two cables (i.e. presence of air bubbles in one cable, different exposure to external temperature, upward and downward facing  portion of the cables and so on);
- in general, the tsunami monitoring gauge instruments are not calibrated to measure tides or absolute quantities, but are set and functioning to only measure relative pressure changes at high frequencies;
- the output is not to be treated as an absolute measurement.

I am closing this ticket even there is no direct resolution, but please feel free to reopen and add any comment / further question if you need!
