### ISSUE TITLE
Recent quakes filtering not working correctly

### ISSUE THREAD

**Issue by core-education** [GeoNet/help#14]
There are 6 quakes I can see in the last 24 hours that are considered severe, but I have to be on the Moderate+ filter to see them. When I select Strong+ or Severe, only one of these severe quakes is displayed.

**Comment by carolinelittle** [comment]
Hi, It's not broken but it is, unfortunately, very confusing.  This is something we've been working on in the mobile apps and we'll apply this to the website in time. 

The filters at the top of the page work on the intensity of the shaking caused by the quake - this is the "Region Intensity" in the list.  The Region Intensity is a calculation of the predicted shaking at the nearest New Zealand town (we're trying to filter the quakes on the effect they have on people).  

Unfortunately we colour and highlight each quake the "Intensity" at the location of the quake, so the maximum calculated intensity. This makes it look like the filters don't work.

I've drawn a little cartoon to illustrate the two different intensities.
![regional vs max intensity](https://cloud.githubusercontent.com/assets/14081509/18234346/fd7f2818-7355-11e6-89c2-562287bdcdaa.jpg)
