### ISSUE TITLE
GLORIA - Rinex data

### ISSUE THREAD

**Issue by pdenys162** [GeoNet/help#47]
The data downloaded using gloria for DOY 218 appears to be partially complete.  Only 4 hours of data is available.  For example, using psudographics (numbers indicate number of GPS SVs tracked, * = > 9): 

WRPA (24hrs data), is included for comparison. 

AVLN |*98*99989888
BLUF |***9***99898
CLIM |****99*9*989
PGNE |*89878989887
SEDD |***89**9*888
TAUP |**999999*987
WARK |**99899**978
WRAU |****9**9*888
WRPA |****9**9*88888**9****9*******9*998798**9888878889998*9899899
 -----+-----------------+-----------------+-----------------+-----------------+
      0                                  12                                  24

pd

**Comment by elidana** [comment]
Hi @pdenys162 ,

I'm glad you are already using the client for GNSS data download! 

The client you are using and its services are still a development version though, as well as the system in the background. Because of that, its functionality and file completeness is not guaranteed. 

I recommend to use the old fashioned ftp until further notice.
