### ISSUE TITLE
New Zephyr 3 Geodetic antennas

### ISSUE THREAD

**Issue by pdenys162** [GeoNet/help#62]
Several of the recently replaced Trimble Alloy/ Zephyr 3 Geodetic antenna appear to have an antenna offset:

DUND   height offset ~10 mm
KTIA                            ~ 9 mm
METH                          ~ 6 mm
WARK                          ~ 12 mm
WHNG east offset       ~ 2 mm

See figure attached for WARK.

Are these new antennas defective? 

![WARK_Time Series](https://user-images.githubusercontent.com/20347984/66888192-143fb680-f03a-11e9-9b97-7d577e5c375c.png)

**Comment by staylorofford** [comment]
Hi @pdenys162,

We are expecting offsets to be introduced by the new antenna model. We produce site ties for each antenna swap which are available at ftp://ftp.geonet.org.nz/gnss/site_ties/ a few days after each swap with some information about what was swapped. Hopefully these can help to remove the offsets you are observing.

**Comment by pdenys162** [comment]
Yes, appreciate that there could be offsets
But we do not see it at all sites.  Therefore, the question to be asked is are the antennas faulty.

Regards
Paul Denys

**Comment by paulagentle** [comment]
@pdenys162 it might be the antenna that has come off the the site WARK.

I completed a local tie survey in 2012 and during the realisation of the ITRF2014 they discovered a 14mm discrepancy in the vertical and 3.9mm in the north between the space geodesy techniques and the local tie.

Id         DOMES    Soln Id    DOMES   Soln East North Up epoch 
WARK 50243M001 1 7377 50243S001 1 **-0.3 -3.9 14.7** 12:338

Refer to:
https://www.iers.org/SharedDocs/Publikationen/EN/IERS/Publications/tn/TechnNote38/tn38.pdf?__blob=publicationFile&v=4 

The new antenna has been calibrated at GA's IGS calibration facility in Canberra.

**Comment by elidana** [comment]
I have informed Sigrun of that as well.
She has processed the data, and also used the tie in data (available from `ftp://ftp.geonet.org.nz/gnss/site_ties`) to better control the offset.

Her results are slightly different from what @pdenys162 is observing, and she wonder if this differences are due to different antenna calibration models used for the processing.

The offsets she records are:

> DUND
> N 3.9 +/- 1.3
> E 2.6 +/- 1.3
> U -1.3 +/- 2.6
> 
> WARK
> N -1.4 +/- 0.8
> E 0.6 +/- 0.7
> U -1.3 +/- 1.7
> 
> These values are completely different from what I would expect when I look at the fits time series.
> Are you guys using the right antenna info? ( I assume so) But also, what antenna phase center model are you guys using for the new antenna?  Old?
> 
> I am concerned about the DUND N and E offset, but the WARK offset is just simply not significant according to the tie data.  So I am a bit baffled by this.
>

**Comment by elidana** [comment]
the antenna model used for the GeoNet standard processing (that feed fits time series) is:

```
TRM115000.00    NONE                                        TYPE / SERIAL NO
ROBOT               Geo++ GmbH               5    22-DEC-16 METH / BY / # / DATE
     5.0                                                    DAZI
     0.0  90.0   5.0                                        ZEN1 / ZEN2 / DZEN
     4                                                      # OF FREQUENCIES
IGS14_2035                                                  SINEX CODE
```

**Comment by pdenys162** [comment]
I use the antenna PCV values as per the I14.ATX file.

             Before                                        After
DUND TRM57971.00     NONE               TRM115000.00    NONE
WARK TRM55971.00     NONE               TRM115000.00    NONE

Based on the rinex file, there has not been any antenna height change. 

The values I have determined for the position time series offset value is based on the L3 (iono free) solution and not on the single frequency tie values. 

pd

**Comment by elidana** [comment]
thanks @pdenys162

**Comment by elidana** [comment]
I have reviewed the antenna offsets on all the Zephyr2 to Zephyr3 swaps done so far.
The vertical offset caused by the antenna swaps is here calculated by the difference between the average of 15 days before and after the swap (excluding the day of the swap). 

In the table below, site code, vertical offset and previous antenna type are listed for PositioNZ the sites that had their antenna changed so far (metadata can be found on the `github.com/GeoNet/delta` repository).

site | vertical offset (mm)
--|--
NPLY | -4.08 | TRM57971.00
LEXA | 0.61 | TRM57971.00
MAVL | 1.92 | TRM57971.00
MAHO | 2.60 | TRM57971.00
HAST | 4.49 | TRM57971.00
TRNG | 5.53 | TRM57971.00
CORM | 6.41 | TRM57971.00
WHNG | 6.57 | TRM57971.00
WANG | 6.85 | TRM57971.00
WHKT | 7.07 | TRM55971.00
HIKB | 7.27 | TRM57971.00
GISB | 7.66 | TRM57971.00
PYGR | 7.98 | TRM57971.00
DNVK | 8.97 | TRM57971.00
WRPA | 9.20 | TRM57971.00
AUCK | 9.37 | TRM57971.00
SCTB | 9.99 | TRM57971.00
HAMT | 13.09 | TRM57971.00
METH | 14.28 | TRM57971.00
DUND | 16.04 | TRM57971.00
WARK | 16.84 | TRM55971.00
KTIA | 17.00 | TRM55971.00
CHTI | 17.35 | TRM55971.00


**Horizontal offsets** (North and East component) are smaller and generally within the expected values ( +/- 2 mm), with the exception of **DUND**, that is showing +4 mm offset on the North and  -2.93 mm on the East component.

Graphs for each station (vertical component) are presented below.
Vertical yellow bar is the day of the antenna change, the blue and orange horizontal lines are the average relative position calculated for 15 days before and after the antenna swap, respectively.

![AUCK](https://user-images.githubusercontent.com/4475504/70084391-1655e700-1673-11ea-9e17-271d01cd12b7.png)
![CHTI](https://user-images.githubusercontent.com/4475504/70084393-1655e700-1673-11ea-993d-893ca6e9483b.png)
![CORM](https://user-images.githubusercontent.com/4475504/70084395-16ee7d80-1673-11ea-9bbe-e4e43dd477bd.png)
![DNVK](https://user-images.githubusercontent.com/4475504/70084396-16ee7d80-1673-11ea-806a-79e260049848.png)
![DUND](https://user-images.githubusercontent.com/4475504/70084398-16ee7d80-1673-11ea-883d-96b8415bc9e9.png)
![GISB](https://user-images.githubusercontent.com/4475504/70084400-17871400-1673-11ea-9342-407dedfdc1aa.png)
![HAMT](https://user-images.githubusercontent.com/4475504/70084401-17871400-1673-11ea-9ad3-053896f347a7.png)
![HAST](https://user-images.githubusercontent.com/4475504/70084402-181faa80-1673-11ea-98a8-6e9d0490a6ca.png)
![HIKB](https://user-images.githubusercontent.com/4475504/70084404-181faa80-1673-11ea-8bb1-5b41801ddae2.png)
![KTIA](https://user-images.githubusercontent.com/4475504/70084405-181faa80-1673-11ea-9231-41c11b2f5cc1.png)
![LEXA](https://user-images.githubusercontent.com/4475504/70084407-18b84100-1673-11ea-9fd9-88fc4ecda243.png)
![MAHO](https://user-images.githubusercontent.com/4475504/70084409-18b84100-1673-11ea-96d8-d5d52dc076b8.png)
![MAVL](https://user-images.githubusercontent.com/4475504/70084410-1950d780-1673-11ea-9061-e3bc5b2134ff.png)
![METH](https://user-images.githubusercontent.com/4475504/70084411-1950d780-1673-11ea-8745-293e5477f56b.png)
![NPLY](https://user-images.githubusercontent.com/4475504/70084413-1950d780-1673-11ea-9907-6a742e316fc6.png)
![PYGR](https://user-images.githubusercontent.com/4475504/70084414-19e96e00-1673-11ea-9641-6133a73961f9.png)
![SCTB](https://user-images.githubusercontent.com/4475504/70084415-19e96e00-1673-11ea-8812-6c7148a8f7b9.png)
![TRNG](https://user-images.githubusercontent.com/4475504/70084416-19e96e00-1673-11ea-878c-32be63a86586.png)
![WANG](https://user-images.githubusercontent.com/4475504/70084418-1a820480-1673-11ea-9747-8b355828305d.png)
![WARK](https://user-images.githubusercontent.com/4475504/70084422-1a820480-1673-11ea-90f2-1c61bf6fd2ee.png)
![WHKT](https://user-images.githubusercontent.com/4475504/70084423-1a820480-1673-11ea-8dbf-230b9d57d1f2.png)
![WHNG](https://user-images.githubusercontent.com/4475504/70084425-1b1a9b00-1673-11ea-8c10-b9794a890635.png)
![WRPA](https://user-images.githubusercontent.com/4475504/70084426-1b1a9b00-1673-11ea-9eef-5f3425c6c4d7.png)
