### ISSUE TITLE
Required FlatFile data for FAS_vertical and PSA_5pc_vertical

### ISSUE THREAD

**Issue by sreenathvemula** [GeoNet/help#77]
In the flatfiles provided for the Fourier, I tried using Matlab function 'FFT' and tried to match with the Fourier spectrum values provided. The shape I obtained matched with that of the FlatFile, but the values had slight discrepancies?

**Comment by sreenathvemula** [comment]
![Fourier GeoMean CCCC2202](https://user-images.githubusercontent.com/15915467/101401110-dd8cc580-38f7-11eb-996b-b49957ab24db.jpg)
I tried plotting Fourier spectra for the earthquake on 22/02/2012 on CCCC site

**Comment by mnaguit** [comment]
Hi. Regarding vertical vs horizontal, there are different number of vertical vs horizontal data because sometimes the vertical data are of lower quality than horizontal, and need to be rejected. The filter cut-off frequencies are determined by plotting the acceleration FAS and finding where spectrum flattens at high and low frequencies. More detail can be found in the publications cited here: https://github.com/GeoNet/data/blob/main/nzsmd-flatfiles/README.md
